print("this is calculation program")
x=int(input("enter the value for x"))
y=int(input("enter the value for y"))
print("equal of x and y:", x==y)
print("lessthan of x and y:", x<y)
print("greaterthan of x and y:", x>y)
print("not equal of x and y:", x!=y)
print("lessthan equal of x and y:", x<=y)
print("greaterthan equal of x and y:", x>=y)
